### ISSUE TITLE
Problem with Pytorch Distributed Training

### ISSUE THREAD

**Issue by ManuelCortes23** [satojkovic/DeepLogo2#4]
Attempting to train a model using the Jupyter notebook:

!python3 detr/main.py \
  --dataset_file "flickr_logos_27" \
  --coco_path "flickr_logos_27_dataset" \
  --output_dir "outputs" \
  --resume "detr-r50_no-class-head.pth" \
  --epochs 100

Results in the following error:

| distributed init (rank 0): env://
Traceback (most recent call last):
  File "/blue/egn4951/manuel.cortes/data/testing_grounds/DeepLogo2/detr/main.py", line 250, in <module>
    main(args)
  File "/blue/egn4951/manuel.cortes/data/testing_grounds/DeepLogo2/detr/main.py", line 108, in main
    utils.init_distributed_mode(args)
  File "/blue/egn4951/manuel.cortes/data/testing_grounds/DeepLogo2/detr/util/misc.py", line 427, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/manuel.cortes/.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/manuel.cortes/.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 255, in _env_rendezvous_handler
    master_addr = _get_env_or_raise("MASTER_ADDR")
  File "/home/manuel.cortes/.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 232, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set

These are all the arguments being passed:

Namespace(lr=0.0001, lr_backbone=1e-05, batch_size=2, weight_decay=0.0001, epochs=100, lr_drop=200, clip_max_norm=0.1, frozen_weights=None, backbone='resnet50', dilation=False, position_embedding='sine', enc_layers=6, dec_layers=6, dim_feedforward=2048, hidden_dim=256, dropout=0.1, nheads=8, num_queries=100, pre_norm=False, masks=False, aux_loss=True, set_cost_class=1, set_cost_bbox=5, set_cost_giou=2, mask_loss_coef=1, dice_loss_coef=1, bbox_loss_coef=5, giou_loss_coef=2, eos_coef=0.1, dataset_file='flickr_logos_27', coco_path='flickr_logos_27_dataset', coco_panoptic_path=None, remove_difficult=False, output_dir='outputs', device='cuda', seed=42, resume='detr-r50_no-class-head.pth', start_epoch=0, eval=False, num_workers=2, world_size=1, dist_url='env://')

The problem seems to be that MASTER_ADDR is not set correctly, if at all. Any way to find a fix for this?

Thank you,
Manuel

**Comment by satojkovic** [comment]
@ManuelCortes23 
Thank you for your interest!

I don't have an environment with multiple GPUs so I can't try it, but specifying 
`torch.distributed.launch` may solve the problem.
Could you try it?

[ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set](https://stackoverflow.com/questions/56805951/valueerror-error-initializing-torch-distributed-using-env-rendezvous-enviro)

**Comment by ManuelCortes23** [comment]
Issue fixed:

`torch.distributed.launch` is depracated, but using `torchrun` solves the problem!
ie.` torchrun detr/main.py --dataset_file "flickr_logos_27" --coco_path "flickr_logos_27_dataset" --output_dir "outputs" --resume "detr-r50_no-class-head.pth" --epochs 100`
